---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace 
        path: /spec/namespaceSelector/matchNames/0
        value: 'demo'
    target:
      group: monitoring.coreos.com
      kind: PodMonitor
      version: v1