apiVersion: v1
kind: Service
metadata:
  name: song
  namespace: song-app
  labels:
    app: song
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: song
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}