---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace 
        path: /spec/installPlanApproval
        value: 'Automatic'
    target:
      group: operators.coreos.com
      kind: Subscription
      name: opentelemetry
      version: v1alpha1