---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-monitor
resources:
  - ../../base
patches:
  # - patch: |-
  #     - op: replace 
  #       path: /spec/installPlanApproval
  #       value: 'Manual'
  #   target:
  #     group: operators.coreos.com
  #     kind: Subscription
  #     name: grafana-operator
  #     version: v1alpha1
  - patch: |-
      - op: replace 
        path: /spec/targetNamespaces/0
        value: 'app-monitor'
    target:
      group: operators.coreos.com
      kind: OperatorGroup
      name: grafana-operator
      version: v1