apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-streams-demo
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: demo
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/amq-streams/instance/overlays/demo
    repoURL: 'https://github.com/rhthsa/amq-streams-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true

