apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-demo
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: app-monitor
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/jaeger/instance/overlays/demo
    repoURL: 'https://github.com/rhthsa/amq-streams-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
