---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base

patches:
  - patch: |-
      - op: replace 
        path: /spec/installPlanApproval
        value: 'Manual'
    target:
      group: operators.coreos.com
      kind: Subscription
      name: amq-streams
      version: v1alpha1