apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: songs
  labels:
    strimzi.io/cluster: kafka-demo
  namespace: demo
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 3
  replicas: 2
  topicName: songs
