---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: music-streaming-app
resources:
  - ../../base
  - config-map.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0
        value:
          configMapRef:
            name: song-indexer-config-demo
    target:
      kind: Deployment
      name: song-indexer
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/voravitl/song-indexer:native-otel
    target:
      kind: Deployment
      name: song-indexer