---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: 'demo'
      - op: replace
        path: /spec/zookeeper/storage/size
        value: '10Gi'
      - op: replace
        path: /spec/kafka/storage/size
        value: '10Gi'
    target:
      kind: Kafka
      group: kafka.strimzi.io
      name: kafka-demo
      version: v1beta2