apiVersion: v1
kind: Service
metadata:
  name: song-indexer
  namespace: song-app
  labels:
    app: song-indexer
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "200"
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: song-indexer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}