apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  config:
    security:
      admin_password: openshift1975
      cookie_secure: true
      login_remember_days: 7
      admin_user: admin
    metrics:
      basic_auth_password: admin
      basic_auth_username: openshift1975
      enabled: true
      interval_seconds: 60
    log:
      level: warn
      mode: console
  ingress:
    enabled: true
