---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  # annotations:
  #   app.quarkus.io/vcs-url: "https://github.com/lordofthejars/kafka-tutorial.git"
  #   app.quarkus.io/build-timestamp: "2020-05-07 - 16:00:40 +0000"
  #   app.quarkus.io/commit-id: "4074464bbd4a3bd3d9f753fa87145fcd5652ddcc"
  labels:
    app.kubernetes.io/name: "song-app-2"
    app.kubernetes.io/version: "quarkus"
  name: "song-app-2"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/voraviz/amq-streams-benchmarking"
    # app.quarkus.io/build-timestamp: "2020-05-07 - 15:38:51 +0000"
    # app.quarkus.io/commit-id: "4074464bbd4a3bd3d9f753fa87145fcd5652ddcc"
  labels:
    app.kubernetes.io/name: "song-app-2"
    app.kubernetes.io/version: "quarkus"
  name: "song-app-2"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "song-app-2"
    app.kubernetes.io/version: "quarkus"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/voraviz/amq-streams-benchmarking"
    # app.quarkus.io/build-timestamp: "2020-05-07 - 15:38:51 +0000"
    # app.quarkus.io/commit-id: "4074464bbd4a3bd3d9f753fa87145fcd5652ddcc"
  labels:
    app.kubernetes.io/name: "song-app-2"
    app.kubernetes.io/version: "quarkus"
  name: "song-app-2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "song-app-2"
      app.kubernetes.io/version: "quarkus"
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: "https://github.com/voraviz/amq-streams-benchmarking"
        # app.quarkus.io/build-timestamp: "2020-05-07 - 15:38:51 +0000"
        # app.quarkus.io/commit-id: "4074464bbd4a3bd3d9f753fa87145fcd5652ddcc"
      labels:
        app.kubernetes.io/name: "song-app-2"
        app.kubernetes.io/version: "quarkus"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "quay.io/voravitl/song:jvm"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/live"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: "song-app-2"
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/ready"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccount: "song-app-2"
