---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-monitor
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace 
        path: /spec/storage/options/memory/max-traces
        value: 50000
    target:
      group: jaegertracing.io
      kind: Jaeger
      name: jaeger
      version: v1