---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace 
        path: /spec/installPlanApproval
        value: 'Automatic'
    target:
      group: operators.coreos.com
      kind: Subscription
      name: amq-streams
      version: v1alpha1
  - patch: |-
      - op: replace 
        path: /spec/targetNamespaces/0
        value: 'demo'
    target:
      group: operators.coreos.com
      kind: OperatorGroup
      name: amq-streams-operator
      version: v1