apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:  # You need to replace PROJECT with namespace/project name
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      jaeger:
        endpoint: jaeger-collector-headless.PROJECT.svc:14250
        tls:
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
          insecure: true
      
    processors:
      batch:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger]
#Set jaeger endpoint to jaeger-collector-headless.CONTROL_PLANE.svc:14250 to export to Service Mesh Jaeger

