---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base
  # - songs-topic.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/zookeeper/storage/size
        value: '10Gi'
      - op: replace
        path: /spec/kafka/storage/size
        value: '12Gi'
    target:
      group: kafka.strimzi.io
      kind: Kafka
      name: kafka-demo
      version: v1beta2